from datetime import date, datetime, timezone

from reviewdigest import render
from reviewdigest.fetch import Review


def _review(rid="1", country="us", rating=5, title="Great", text="Love it"):
    return Review(
        id=rid, app_id="42", country=country,
        date=datetime(2026, 7, 9, tzinfo=timezone.utc),
        rating=rating, title=title, text=text, author="u",
    )


def test_stats_normal():
    md = render.render_app_stats(
        "MyApp",
        [_review(), _review("2", rating=1, country="jp")],
        {"us": {"average_rating": 4.5, "rating_count": 100}},
        {"us": {"average_rating": 4.4, "rating_count": 90}},
    )
    assert "## MyApp" in md
    assert "2 new reviews" in md
    assert "US 1" in md and "JP 1" in md
    assert "(+0.10)" in md  # week-over-week delta


def test_stats_no_reviews():
    md = render.render_app_stats("MyApp", [], {}, {})
    assert "No new reviews" in md


def test_raw_reviews_groups_by_rating_worst_first():
    md = render.render_raw_reviews([_review(rating=5), _review("2", rating=1)])
    assert md.index("1★") < md.index("5★")


def test_digest_assembles():
    md = render.render_digest(date(2026, 7, 2), date(2026, 7, 10), ["## A\nsection"])
    assert md.startswith("# 📱 Review Digest")
    assert "## A" in md
    assert "Generated by reviewdigest" in md


def test_issue_title_single_and_multi():
    t1 = render.issue_title(date(2026, 7, 2), date(2026, 7, 10), 5, ["MyApp"])
    assert "MyApp" in t1 and "5 new reviews" in t1
    t2 = render.issue_title(date(2026, 7, 2), date(2026, 7, 10), 1, ["A", "B"])
    assert "2 apps" in t2 and "1 new review" in t2
