"""Render the weekly digest markdown: computed stats + LLM analysis body."""

from __future__ import annotations

from collections import Counter
from datetime import date

from .fetch import Review

STAR = "★"


def _stars_bar(count: int, total: int, width: int = 20) -> str:
    if total == 0:
        return ""
    filled = round(width * count / total)
    return "█" * filled + "░" * (width - filled)


def _fmt_rating(value) -> str:
    return f"{value:.2f}" if isinstance(value, (int, float)) else "–"


def render_app_stats(
    app_name: str,
    reviews: list[Review],
    store_ratings: dict[str, dict],
    previous_ratings: dict[str, dict],
) -> str:
    """Computed, non-LLM stats block for one app."""
    lines = [f"## {app_name}", ""]
    total = len(reviews)
    if total:
        avg = sum(r.rating for r in reviews) / total
        by_country = Counter(r.country for r in reviews)
        n_countries = len(by_country)
        lines.append(
            f"**{total} new review{'s' if total != 1 else ''}** across "
            f"{n_countries} storefront{'s' if n_countries != 1 else ''} · "
            f"average {avg:.1f}{STAR}"
        )
        lines.append("")
        hist = Counter(r.rating for r in reviews)
        for stars in range(5, 0, -1):
            c = hist.get(stars, 0)
            lines.append(f"`{stars}{STAR} {_stars_bar(c, total)} {c}`  ")
        lines.append("")
        top = by_country.most_common(10)
        parts = [f"{cc.upper()} {n}" for cc, n in top]
        if len(by_country) > 10:
            parts.append(f"+{len(by_country) - 10} more")
        lines.append("New reviews by storefront: " + " · ".join(parts))
    else:
        lines.append("**No new reviews this period.**")
    lines.append("")

    # Store-rating snapshot with week-over-week delta where we have history.
    snapshot_lines = []
    for cc, cur in sorted(store_ratings.items()):
        if cur is None or cur.get("average_rating") is None:
            continue
        prev = previous_ratings.get(cc)
        delta = ""
        if prev and isinstance(prev.get("average_rating"), (int, float)) and isinstance(
            cur.get("average_rating"), (int, float)
        ):
            diff = cur["average_rating"] - prev["average_rating"]
            if abs(diff) >= 0.005:
                delta = f" ({'+' if diff > 0 else ''}{diff:.2f})"
        count = cur.get("rating_count")
        count_s = f", {count:,} ratings" if isinstance(count, int) else ""
        snapshot_lines.append(
            f"- {cc.upper()}: {_fmt_rating(cur.get('average_rating'))}{STAR}{delta}{count_s}"
        )
    if snapshot_lines:
        lines.append("<details><summary>Store rating by storefront</summary>")
        lines.append("")
        lines.extend(snapshot_lines)
        lines.append("")
        lines.append("</details>")
        lines.append("")
    return "\n".join(lines)


def render_raw_reviews(reviews: list[Review], limit: int = 100) -> str:
    """No-LLM fallback: list new reviews grouped by rating, worst first."""
    if not reviews:
        return ""
    lines = ["### New reviews (raw — set an LLM API key for AI analysis)", ""]
    shown = 0
    for stars in range(1, 6):
        bucket = sorted(
            (r for r in reviews if r.rating == stars), key=lambda r: r.date, reverse=True
        )
        if not bucket:
            continue
        lines.append(f"#### {stars}{STAR} ({len(bucket)})")
        for r in bucket:
            if shown >= limit:
                lines.append(f"…and {len(reviews) - shown} more (raised `output` limit needed).")
                return "\n".join(lines)
            title = f"**{r.title}** — " if r.title else ""
            body = r.text if len(r.text) <= 400 else r.text[:400] + "…"
            lines.append(f"- [{r.country.upper()} {r.date.date().isoformat()}] {title}{body}")
            shown += 1
        lines.append("")
    return "\n".join(lines)


def render_digest(
    period_start: date,
    period_end: date,
    app_sections: list[str],
    footer_note: str = "",
) -> str:
    header = f"# 📱 Review Digest · {period_start.strftime('%b %-d')} – {period_end.strftime('%b %-d, %Y')}"
    parts = [header, ""]
    parts.extend(app_sections)
    parts.append("---")
    parts.append(
        "*Generated by [reviewdigest](https://github.com/dingdugan/review.digest) — "
        "open-source App Store review digests as GitHub Issues.*"
        + (f" {footer_note}" if footer_note else "")
    )
    return "\n".join(parts)


def issue_title(period_start: date, period_end: date, total_new: int, app_names: list[str]) -> str:
    apps = app_names[0] if len(app_names) == 1 else f"{len(app_names)} apps"
    return (
        f"📱 Review Digest {period_start.strftime('%b %-d')} – "
        f"{period_end.strftime('%b %-d, %Y')} · {apps} · {total_new} new review"
        f"{'s' if total_new != 1 else ''}"
    )
