"""Build the static dashboard site from digests/ + state/state.json.

Output goes to _site/ (index.html, one page per digest, setup wizard).
Run as `python -m reviewdigest.site`; the workflow publishes _site/ to
GitHub Pages. No JS frameworks — hand-rendered HTML, inline CSS, and
inline SVG for the rating-trend chart.
"""

from __future__ import annotations

import html
import json
import os
import re
import shutil
import sys

import markdown

from . import state as state_mod
from .config import load as load_config, ConfigError

SITE_SRC_DIR = "site"  # static assets (setup.html) copied verbatim
OUTPUT_DIR = "_site"
TREND_POINTS = 26  # ~ half a year of weekly snapshots
TREND_COUNTRIES = 6  # most-rated storefronts shown on the chart

CSS = """
:root {
  --bg: #ffffff; --fg: #1a1a1a; --muted: #6b7280; --line: #e5e7eb;
  --accent: #0969da; --card: #f6f8fa;
}
@media (prefers-color-scheme: dark) {
  :root { --bg: #0d1117; --fg: #e6edf3; --muted: #8b949e; --line: #30363d;
          --accent: #58a6ff; --card: #161b22; }
}
* { box-sizing: border-box; }
body { margin: 0 auto; max-width: 760px; padding: 2rem 1.25rem 4rem;
       background: var(--bg); color: var(--fg);
       font: 16px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
h1 { font-size: 1.6rem; } h2 { font-size: 1.3rem; margin-top: 2rem; }
h3 { font-size: 1.05rem; margin-top: 1.6rem; }
blockquote { margin: .5rem 0; padding: .3rem .9rem; border-left: 3px solid var(--line);
             color: var(--muted); }
code { background: var(--card); padding: .1rem .3rem; border-radius: 4px;
       font-size: .85em; }
header.site { display: flex; justify-content: space-between; align-items: baseline;
              border-bottom: 1px solid var(--line); padding-bottom: .8rem;
              margin-bottom: 1.5rem; }
header.site .brand { font-weight: 700; font-size: 1.1rem; color: var(--fg); }
header.site nav a { margin-left: 1rem; font-size: .9rem; }
ul.digest-list { list-style: none; padding: 0; }
ul.digest-list li { padding: .55rem 0; border-bottom: 1px solid var(--line);
                    display: flex; justify-content: space-between; gap: 1rem; }
ul.digest-list .meta { color: var(--muted); font-size: .85rem; white-space: nowrap; }
.chart-card { background: var(--card); border: 1px solid var(--line);
              border-radius: 8px; padding: 1rem; margin: 1rem 0; }
.chart-card svg { width: 100%; height: auto; display: block; }
.legend { display: flex; flex-wrap: wrap; gap: .4rem 1rem; margin-top: .5rem;
          font-size: .8rem; color: var(--muted); }
.legend .dot { display: inline-block; width: 10px; height: 10px;
               border-radius: 50%; margin-right: .3rem; }
.empty { color: var(--muted); background: var(--card); border: 1px dashed var(--line);
         border-radius: 8px; padding: 1.5rem; text-align: center; margin: 2rem 0; }
footer { margin-top: 3rem; color: var(--muted); font-size: .8rem;
         border-top: 1px solid var(--line); padding-top: 1rem; }
"""

LINE_COLORS = ["#0969da", "#d4a72c", "#1a7f37", "#cf222e", "#8250df", "#bc4c00"]


def _page(title: str, body: str, root: str = "") -> str:
    return f"""<!doctype html>
<html lang="en">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title>
<style>{CSS}</style>
<body>
<header class="site">
  <a class="brand" href="{root}index.html">&#128241; reviewdigest</a>
  <nav><a href="{root}index.html">Dashboard</a><a href="{root}setup.html">Setup wizard</a></nav>
</header>
{body}
<footer>Generated by <a href="https://github.com/dingdugan/review.digest">reviewdigest</a> — open-source App Store review digests.</footer>
</body>
</html>
"""


def _digest_title(md_text: str, fallback: str) -> str:
    m = re.search(r"^<!--\s*(.+?)\s*-->", md_text)
    if m:
        return m.group(1)
    m = re.search(r"^# (.+)$", md_text, re.M)
    return m.group(1) if m else fallback


def _digest_summary(md_text: str) -> str:
    m = re.search(r"\*\*(\d+ new reviews?)\*\*", md_text)
    return m.group(1) if m else ""


def render_trend_svg(histories: dict[str, list[dict]]) -> str:
    """Inline SVG line chart of average store rating per storefront over time.

    `histories` maps a storefront code to its rating-snapshot list
    (each entry: {"date", "average_rating", "rating_count"}).
    """
    series = []
    for cc, hist in histories.items():
        points = [
            (h["date"], float(h["average_rating"]))
            for h in hist[-TREND_POINTS:]
            if isinstance(h.get("average_rating"), (int, float))
        ]
        if points:
            count = hist[-1].get("rating_count") or 0
            series.append((cc, points, count))
    series.sort(key=lambda s: -s[2])
    series = series[:TREND_COUNTRIES]
    if not series or all(len(pts) < 2 for _, pts, _ in series):
        return ""

    all_vals = [v for _, pts, _ in series for _, v in pts]
    all_dates = sorted({d for _, pts, _ in series for d, _ in pts})
    lo = min(all_vals) - 0.05
    hi = max(all_vals) + 0.05
    if hi - lo < 0.1:
        mid = (hi + lo) / 2
        lo, hi = mid - 0.05, mid + 0.05
    W, H, PAD_L, PAD_R, PAD_T, PAD_B = 720, 220, 44, 10, 10, 24
    date_x = {
        d: PAD_L + (W - PAD_L - PAD_R) * (i / max(1, len(all_dates) - 1))
        for i, d in enumerate(all_dates)
    }

    def y(v: float) -> float:
        return PAD_T + (H - PAD_T - PAD_B) * (1 - (v - lo) / (hi - lo))

    parts = [f'<svg viewBox="0 0 {W} {H}" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Store rating trend">']
    for frac in (0, 0.5, 1):
        val = lo + (hi - lo) * frac
        gy = y(val)
        parts.append(
            f'<line x1="{PAD_L}" y1="{gy:.1f}" x2="{W - PAD_R}" y2="{gy:.1f}" stroke="#80808040" stroke-width="1"/>'
            f'<text x="{PAD_L - 6}" y="{gy + 4:.1f}" text-anchor="end" font-size="11" fill="#808080">{val:.2f}</text>'
        )
    parts.append(
        f'<text x="{PAD_L}" y="{H - 6}" font-size="11" fill="#808080">{html.escape(all_dates[0])}</text>'
        f'<text x="{W - PAD_R}" y="{H - 6}" text-anchor="end" font-size="11" fill="#808080">{html.escape(all_dates[-1])}</text>'
    )
    legend = []
    for i, (cc, pts, _) in enumerate(series):
        color = LINE_COLORS[i % len(LINE_COLORS)]
        coords = " ".join(f"{date_x[d]:.1f},{y(v):.1f}" for d, v in pts)
        parts.append(
            f'<polyline points="{coords}" fill="none" stroke="{color}" stroke-width="2" stroke-linejoin="round"/>'
        )
        last_d, last_v = pts[-1]
        parts.append(f'<circle cx="{date_x[last_d]:.1f}" cy="{y(last_v):.1f}" r="3" fill="{color}"/>')
        legend.append(
            f'<span><span class="dot" style="background:{color}"></span>{cc.upper()} {last_v:.2f}&#9733;</span>'
        )
    parts.append("</svg>")
    return "".join(parts) + f'<div class="legend">{"".join(legend)}</div>'


def build(digests_dir: str = "digests", state_path: str = "state/state.json",
          out_dir: str = OUTPUT_DIR, site_src: str = SITE_SRC_DIR,
          config_path: str = "reviewdigest.yaml") -> None:
    os.makedirs(out_dir, exist_ok=True)

    # 1. Copy static assets (setup wizard).
    if os.path.isdir(site_src):
        for name in os.listdir(site_src):
            shutil.copy(os.path.join(site_src, name), os.path.join(out_dir, name))

    # 2. Render each digest markdown to its own page.
    entries = []
    if os.path.isdir(digests_dir):
        for name in sorted(os.listdir(digests_dir), reverse=True):
            if not name.endswith(".md"):
                continue
            with open(os.path.join(digests_dir, name), encoding="utf-8") as f:
                md_text = f.read()
            page_name = name[:-3] + ".html"
            title = _digest_title(md_text, name[:-3])
            body = markdown.markdown(md_text, extensions=["md_in_html"])
            with open(os.path.join(out_dir, page_name), "w", encoding="utf-8") as f:
                f.write(_page(title, body))
            entries.append({"page": page_name, "title": title,
                            "summary": _digest_summary(md_text)})

    # 3. Trend chart per app from the rating history in state.json.
    app_names = {}
    try:
        cfg = load_config(config_path)
        app_names = {a.id: a.name for a in cfg.apps}
    except ConfigError:
        pass
    charts = []
    state = state_mod.load(state_path)
    by_app: dict[str, dict[str, list[dict]]] = {}
    for key, hist in state.get("ratings", {}).items():
        app_id, _, cc = key.partition(":")
        by_app.setdefault(app_id, {})[cc] = hist
    for app_id, histories in by_app.items():
        svg = render_trend_svg(histories)
        if svg:
            label = (app_names.get(app_id) or state.get("names", {}).get(app_id)
                     or f"App {app_id}")
            charts.append(
                f"<h2>{html.escape(label)} — store rating trend</h2>"
                f'<div class="chart-card">{svg}</div>'
            )

    # 4. Index page.
    if entries:
        items = "".join(
            f'<li><a href="{e["page"]}">{html.escape(e["title"])}</a></li>'
            for e in entries
        )
        digest_block = f"<h2>Weekly digests</h2><ul class=\"digest-list\">{items}</ul>"
    else:
        digest_block = (
            '<div class="empty">No digests yet. The first one appears after the '
            "weekly workflow runs (or trigger it manually from the Actions tab).</div>"
        )
    index_body = "<h1>Review dashboard</h1>" + "".join(charts) + digest_block
    with open(os.path.join(out_dir, "index.html"), "w", encoding="utf-8") as f:
        f.write(_page("Review dashboard — reviewdigest", index_body))

    print(f"site built: {out_dir}/ ({len(entries)} digest page(s), {len(charts)} chart(s))")


if __name__ == "__main__":
    build(*sys.argv[1:])
